ModelFinetuner:
  direct_upsample_rate: -1
  distill_mode: false
  down_sample_amount: -1
  ensemble_distill_mode: false
  language_resample: false
  train_with_professor: false
dependency:
  Corpus: UD_English-EWT:UD_Hebrew-HTB:UD_Japanese-GSD:UD_Slovenian-SST:UD_French-Sequoia:UD_Indonesian-GSD:UD_Persian-Seraji:UD_Tamil-TTB:UD_Dutch-LassySmall:UD_German-GSD:UD_Swedish-LinES:UD_Italian-PoSTWITA:UD_Spanish-GSD
  tag_dictionary: resources/taggers/ud_dependency_tags.pkl
  teachers:
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_de_monolingual_nocrf_fast_nodev_dependency0.yaml
    : UD_German-GSD
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_en_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_English-EWT
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_es_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Spanish-GSD
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_fa_monolingual_nocrf_fast_nodev_dependency0.yaml
    : UD_Persian-Seraji
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_fr_monolingual_nocrf_fast_nodev_dependency0.yaml
    : UD_French-Sequoia
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_he_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Hebrew-HTB
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_id_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Indonesian-GSD
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_it_monolingual_nocrf_fast_nodev_dependency0.yaml
    : UD_Italian-PoSTWITA
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_ja_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Japanese-GSD
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_nl_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Dutch-LassySmall
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_sl_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Slovenian-SST
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_sv_monolingual_nocrf_fast_nodev_dependency0.yaml
    : UD_Swedish-LinES
    ? config_gen/multi_bert_word_origflair_1000epoch_0.5inter_3000batch_0.002lr_400hidden_ta_monolingual_nocrf_fast_nodev_dependency1.yaml
    : UD_Tamil-TTB
embeddings:
  BertEmbeddings:
    bert_model_or_path: bert-base-multilingual-cased
    fine_tune: true
    layers: '-1'
    pooling_operation: mean
    sentence_feat: false
is_teacher_list: true
is_toy: false
model:
  SemanticDependencyParser:
    binary: false
    diagonal: false
    factorize: true
    hidden_size: 400
    init_std: 0.25
    interpolation: 0.5
    iterations: 3
    lstm_dropout: 0.33
    mlp_dropout: 0.33
    n_mlp_arc: 500
    n_mlp_rel: 100
    n_mlp_sec: 150
    rnn_layers: 3
    tree: true
    use_cop: true
    use_crf: false
    use_gp: true
    use_rnn: false
    use_second_order: false
    use_sib: true
    word_dropout: 0.33
model_name: multi_bert_10epoch_0.5inter_3000batch_0.00005lr_20lrrate_multilingual_nocrf_fast_warmup_freezing_beta_weightdecay_finetune_nodev_dependency15
target_dir: resources/taggers/
targets: dependency
teacher_annealing: false
train:
  best_k: 5
  betas:
  - 0.9
  - 0.99
  calc_teachers_target_loss: false
  entropy_loss_rate: 0.001
  fine_tune_mode: true
  freezing: true
  language_attention_entropy: false
  language_attention_warmup: false
  language_attention_warmup_and_fix: false
  learning_rate: 5.0e-05
  lr_rate: 20
  max_epochs: 10
  min_freq: 2
  mini_batch_size: 3000
  monitor_test: false
  rootschedule: false
  save_final_model: false
  sort_data: true
  train_language_attention_by_dev: false
  train_with_dev: false
  true_reshuffle: false
  use_unlabeled_data: false
  use_warmup: true
  weightdecay: 0.01
trainer: ModelFinetuner
